//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ashyana.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class a
    {
        public int linkID { get; set; }
        public string linkName { get; set; }
        public string linkPath { get; set; }
        public Nullable<int> linkRank { get; set; }
        public Nullable<int> linkforHome { get; set; }
        public string linkDesc { get; set; }
        public Nullable<int> linkDelete { get; set; }
        public Nullable<int> linkCreatedBy { get; set; }
        public Nullable<System.DateTime> linkCreatedOn { get; set; }
        public Nullable<int> linkDeletedBy { get; set; }
        public Nullable<System.DateTime> linkDeletedOn { get; set; }
        public Nullable<int> linkUpdatedBy { get; set; }
        public Nullable<System.DateTime> linkUpdatedOn { get; set; }
    }
}
