//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ashyana.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Building
    {
        public int buildingTypeID { get; set; }
        public string buildingType { get; set; }
        public string buildingDesc { get; set; }
        public string buildingImage { get; set; }
        public Nullable<int> buildingDelete { get; set; }
        public Nullable<System.DateTime> buildingDeletedon { get; set; }
        public Nullable<int> buildingCreatedby { get; set; }
        public Nullable<System.DateTime> buildingCreatedon { get; set; }
        public Nullable<int> buildingDeletedby { get; set; }
        public Nullable<int> buildingUpdatedby { get; set; }
        public Nullable<System.DateTime> buildingUpdatedon { get; set; }
    }
}
