//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ashyana.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactInfo
    {
        public int contactID { get; set; }
        public string contact_name { get; set; }
        public string contact_EmailID { get; set; }
        public string contact_No { get; set; }
        public string contact_desc { get; set; }
        public Nullable<System.DateTime> contactCreatedOn { get; set; }
        public Nullable<System.DateTime> contactDeletedOn { get; set; }
    }
}
