//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ashyana.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public int CountryID { get; set; }
        public string CountryName { get; set; }
        public string CountryDesc { get; set; }
        public string CountryImage { get; set; }
        public Nullable<int> CountryDelete { get; set; }
        public Nullable<int> CountryCreatedby { get; set; }
        public Nullable<System.DateTime> CountryCreatedon { get; set; }
        public Nullable<int> CountryDeletedby { get; set; }
        public Nullable<System.DateTime> CountryDeletedon { get; set; }
        public Nullable<int> CountryUpdatedby { get; set; }
        public Nullable<System.DateTime> CountryUpdatedon { get; set; }
    }
}
