//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ashyana.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Floor
    {
        public int floorTypeID { get; set; }
        public string floorType { get; set; }
        public string floorDesc { get; set; }
        public string floorImage { get; set; }
        public Nullable<int> floorDelete { get; set; }
        public Nullable<System.DateTime> floorDeletedon { get; set; }
        public Nullable<int> floorCreatedby { get; set; }
        public Nullable<System.DateTime> floorCreatedon { get; set; }
        public Nullable<int> floorDeletedby { get; set; }
        public Nullable<int> floorUpdatedby { get; set; }
        public Nullable<System.DateTime> floorUpdatedon { get; set; }
    }
}
