//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ashyana.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mail
    {
        public int mailID { get; set; }
        public string mailDesc { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<int> PropertyID { get; set; }
        public Nullable<System.DateTime> scheduleDate { get; set; }
        public Nullable<int> mailDelete { get; set; }
        public Nullable<int> mailCreatedBy { get; set; }
        public Nullable<System.DateTime> mailCreatedOn { get; set; }
    }
}
