//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ashyana.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MapuserRoleLink
    {
        public int userLinkMapID { get; set; }
        public Nullable<int> roleID { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<int> linkID { get; set; }
        public Nullable<int> subLinkID { get; set; }
        public Nullable<int> sublinkView { get; set; }
        public Nullable<int> sublinkAdd { get; set; }
        public Nullable<int> sublinkUpdate { get; set; }
        public Nullable<int> sublinkDelete { get; set; }
        public Nullable<int> sublinkPrint { get; set; }
        public int linkCheck { get; set; }
        public int subLinkcheck { get; set; }
        public Nullable<int> linkCreatedBy { get; set; }
        public Nullable<System.DateTime> linkCreatedOn { get; set; }
        public Nullable<int> linkDeletedBy { get; set; }
        public Nullable<System.DateTime> linkDeletedOn { get; set; }
        public Nullable<int> linkUpdatedBy { get; set; }
        public Nullable<System.DateTime> linkUpdatedOn { get; set; }
    }
}
