//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ashyana.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyType
    {
        public int propertyTypeID { get; set; }
        public string propertyType1 { get; set; }
        public string propertyTypeDesc { get; set; }
        public Nullable<int> propertyTypeDelete { get; set; }
        public Nullable<System.DateTime> propertyTypeDeletedOn { get; set; }
        public Nullable<int> propertyTypeCreatedBy { get; set; }
        public Nullable<System.DateTime> propertyTypeCreatedOn { get; set; }
        public Nullable<int> propertyTypeUpdatedBy { get; set; }
        public Nullable<System.DateTime> propertyTypeUpdatedOn { get; set; }
    }
}
