//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ashyana.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public int purchaseTypeID { get; set; }
        public string purchaseDesc { get; set; }
        public string purchaseImage { get; set; }
        public Nullable<int> purchaseDelete { get; set; }
        public Nullable<int> purchaseCreatedBy { get; set; }
        public Nullable<System.DateTime> purchaseCreatedOn { get; set; }
        public Nullable<int> purchaseDeletedBy { get; set; }
        public Nullable<System.DateTime> purchaseDeletedOn { get; set; }
        public Nullable<int> purchaseUpdatedBy { get; set; }
        public string purchaseUpdatedOn { get; set; }
    }
}
