//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ashyana.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public int roleID { get; set; }
        public string roleName { get; set; }
        public string roleDescription { get; set; }
        public int roleDelete { get; set; }
        public Nullable<int> roleCreatedBy { get; set; }
        public Nullable<System.DateTime> roleCreatedOn { get; set; }
        public Nullable<int> roleDeletedBy { get; set; }
        public Nullable<System.DateTime> roleDeletedOn { get; set; }
        public Nullable<int> roleUpdatedBy { get; set; }
        public Nullable<System.DateTime> roleUpdatedOn { get; set; }
    }
}
