//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ashyana.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class State
    {
        public int StateID { get; set; }
        public string StateName { get; set; }
        public string StateDesc { get; set; }
        public string StateImage { get; set; }
        public Nullable<int> StateDelete { get; set; }
        public Nullable<int> StateCreatedby { get; set; }
        public Nullable<System.DateTime> StateCreatedon { get; set; }
        public Nullable<int> StateDeletedby { get; set; }
        public Nullable<System.DateTime> StateDeletedon { get; set; }
        public Nullable<int> StateUpdatedby { get; set; }
        public Nullable<System.DateTime> StateUpdatedon { get; set; }
        public Nullable<int> countryID { get; set; }
    }
}
