//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ashyana.UI.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agent
    {
        public int agentID { get; set; }
        public string dealingIn { get; set; }
        public Nullable<int> cityID { get; set; }
        public string propertyHandled { get; set; }
        public string locality { get; set; }
        public Nullable<int> agentDelete { get; set; }
        public Nullable<System.DateTime> agentCreatedOn { get; set; }
        public Nullable<int> agentCreatedBy { get; set; }
        public Nullable<System.DateTime> agentDeletedOn { get; set; }
        public Nullable<int> agentDeletedBy { get; set; }
        public Nullable<System.DateTime> agentUpdatedOn { get; set; }
        public Nullable<int> agentUpdatedBy { get; set; }
    }
}
