//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ashyana.UI.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public City()
        {
            this.Users = new HashSet<User>();
        }
    
        public int CityID { get; set; }
        public string CityName { get; set; }
        public string CityDesc { get; set; }
        public Nullable<int> CityForHome { get; set; }
        public string CityImage { get; set; }
        public Nullable<int> CityDelete { get; set; }
        public Nullable<int> CityCreatedby { get; set; }
        public Nullable<System.DateTime> CityCreatedon { get; set; }
        public Nullable<int> CityDeletedby { get; set; }
        public Nullable<System.DateTime> CityDeletedon { get; set; }
        public Nullable<int> CityUpdatedby { get; set; }
        public Nullable<System.DateTime> CityUpdatedon { get; set; }
        public Nullable<int> countryID { get; set; }
        public Nullable<int> StateID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
    }
}
