//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ashyana.UI.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Country()
        {
            this.Users = new HashSet<User>();
        }
    
        public int CountryID { get; set; }
        public string CountryName { get; set; }
        public string CountryDesc { get; set; }
        public string CountryImage { get; set; }
        public Nullable<int> CountryDelete { get; set; }
        public Nullable<int> CountryCreatedby { get; set; }
        public Nullable<System.DateTime> CountryCreatedon { get; set; }
        public Nullable<int> CountryDeletedby { get; set; }
        public Nullable<System.DateTime> CountryDeletedon { get; set; }
        public Nullable<int> CountryUpdatedby { get; set; }
        public Nullable<System.DateTime> CountryUpdatedon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
    }
}
