//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ashyana.UI.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int NewsID { get; set; }
        public string NewsType { get; set; }
        public string NewsDesc { get; set; }
        public string NewsImage { get; set; }
        public Nullable<int> NewsDelete { get; set; }
        public Nullable<System.DateTime> NewsDeletedon { get; set; }
        public Nullable<int> NewsCreatedby { get; set; }
        public Nullable<System.DateTime> NewsCreatedon { get; set; }
        public Nullable<int> NewsDeletedby { get; set; }
        public Nullable<int> NewsUpdatedby { get; set; }
        public Nullable<System.DateTime> NewsUpdatedon { get; set; }
    }
}
