//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ashyana.UI.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhoneType
    {
        public int PhoneTypeID { get; set; }
        public string PhoneTypeName { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual User User { get; set; }
    }
}
