//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ashyana.UI.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        public int propertyID { get; set; }
        public Nullable<int> propertyTypeID { get; set; }
        public string propertyDesc { get; set; }
        public string purchaseType { get; set; }
        public Nullable<decimal> propertyPrice { get; set; }
        public Nullable<int> bedroom { get; set; }
        public string propertyArea { get; set; }
        public Nullable<int> countryID { get; set; }
        public Nullable<int> stateID { get; set; }
        public Nullable<int> cityID { get; set; }
        public string metro { get; set; }
        public string propertyAddress { get; set; }
        public string propertyLocality { get; set; }
        public Nullable<int> pin { get; set; }
        public Nullable<int> propertyAge { get; set; }
        public Nullable<decimal> propertyTenure { get; set; }
        public string propertyImage { get; set; }
        public int propertyDelete { get; set; }
        public Nullable<System.DateTime> propertyDeletedon { get; set; }
        public Nullable<int> propertyCreatedby { get; set; }
        public Nullable<System.DateTime> propertyCreatedon { get; set; }
        public Nullable<int> propertyDeletedby { get; set; }
        public Nullable<int> propertyUpdatedby { get; set; }
        public Nullable<System.DateTime> propertyUpdatedon { get; set; }


        public string  propertyTypeName { get; set; }
        public string CountryName { get; set; }
        public string StateName { get; set; }

        public string CityName { get; set; }

    }
}
