//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ashyana.UI.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubLink
    {
        public int subLinkID { get; set; }
        public Nullable<int> linkID { get; set; }
        public string subLinkName { get; set; }
        public string subLinkPath { get; set; }
        public Nullable<int> subLinkRank { get; set; }
        public Nullable<int> subLinkDelete { get; set; }
        public Nullable<int> subLinkView { get; set; }
        public Nullable<int> subLinkAdd { get; set; }
        public Nullable<int> sublinkUpdate { get; set; }
        public Nullable<int> sublinkPrint { get; set; }
        public Nullable<int> subLinkCreatedBy { get; set; }
        public Nullable<System.DateTime> subLinkCreatedOn { get; set; }
        public Nullable<int> subLinkDeletedBy { get; set; }
        public Nullable<System.DateTime> subLinkDeletedOn { get; set; }
        public Nullable<int> subLinkUpdatedBy { get; set; }
        public Nullable<System.DateTime> subLinkUpdatedOn { get; set; }
    }
}
