//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ashyana.UI.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.PhoneTypes = new HashSet<PhoneType>();
        }
    
        public int userID { get; set; }
        public string userFirstname { get; set; }
        public string userLastname { get; set; }
        public string userEmailID { get; set; }
        public string userContactno { get; set; }
        public string userName { get; set; }
        public Nullable<int> RoleID { get; set; }
        public Nullable<int> countryID { get; set; }
        public Nullable<int> StateID { get; set; }
        public Nullable<int> cityID { get; set; }
        public int userDelete { get; set; }
        public string userPassword { get; set; }
        public int userCreatedBy { get; set; }
        public Nullable<System.DateTime> userCreatedOn { get; set; }
        public Nullable<int> userDeletedBy { get; set; }
        public Nullable<System.DateTime> userDeletedOn { get; set; }
        public Nullable<int> userUpdatedBy { get; set; }
        public Nullable<System.DateTime> userUpdatedOn { get; set; }
    
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhoneType> PhoneTypes { get; set; }
        public virtual State State { get; set; }
    }
}
